version: "3.8"

services:
  foundation:
    image: postgres:17.4-alpine3.21
    container_name: foundation_db
    env_file:
      - ../.env.development
    ports:
      - "5433:5432"
    volumes:
      - pgdata_foundation:/var/lib/postgresql/data

volumes:
  pgdata_foundation:
